inherits                          = "lilka"

"ui.virtual.inlay-hint"           = { fg = "pale", bg = "none" }
# "ui.virtual.inlay-hint.parameter" = { fg = "pale", bg = "none"}
# "ui.virtual.inlay-hint.type"      = { fg = "pale", bg = "none"}
"ui.menu.selected"                = { modifiers = ["reversed"] }


"diagnostic.warning"              = { fg = "dark" }
"diagnostic.info"                 = { fg = "dark" }
"diagnostic.hint"                 = { fg = "dark" }
"diagnostic.error"                = { fg = "dark" }

"ui.selection"                    = { fg = "grey", underline = { style = "line" }, modifiers = ["bold"] }
"attribute"                       = "dark"
"comment"                         = { fg = "dark", modifiers = ["italic"]}
"type"                            = "grey"
"warning"                         = "dark"
"info"                            = "dark"
"hint"                            = "dark"
"constructor"                     = "dark"
"constant"                        = "dim"
"string"                          = "pale"
"variable"                        = "dim"
"operator"                        = "pale"
"function"                        = "dim"
"namespace"                       = "dim"


